M48
; DRILL file KiCad 10.0.6 date 2026-09-15T23:19:14
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-15T23:19:14-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X25.11Y-7.3
X30.89Y-7.3
T2
X4.0Y-4.0
X4.0Y-56.0
X86.0Y-4.0
X86.0Y-56.0
M30
