M48
; DRILL file KiCad 10.0.6 date 2026-10-05T18:03:56
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-05T18:03:56-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X27.11Y-47.755
X32.89Y-47.755
T2
X3.5Y-51.5
X43.0Y-10.0
M30
